### ISSUE TITLE
Vagrant image intermittently fails to bring up networking

### ISSUE THREAD

**Issue by karmix** [CentOS/sig-cloud-instance-build#24]
The vagrant box CentOS-7-Vagrant-1508-x86_64-01.box intermittently fails to bring up networking when used in a configuration with more than one network adapter.  This is because the 'eth0' connection profile is not associated with any specific interface.  When NetworkManager tries to bring the 'eth0' connection up on a non-eth0 device (that is not on a network with a DHCP server), it logs a failure message such as:

network: Bringing up interface eth0:  Error: Connection activation failed: Connection 'eth0' is already active on eth1

**Comment by kbsingh** [comment]
merged, thanks. this would be included in the next update image set, due on the 28th Oct.

**Comment by lpancescu** [comment]
I'm afraid this issue is NOT fixed. With the 1601.01 CentOS image, using Vagrant with VirtualBox 5.0.14 on OS X 10.11, quite often there's either no device or the wrong device associated with `eth0`:
```
[vagrant@localhost ~]$ sudo nmcli show
NAME  UUID                                  TYPE            DEVICE
eth0  64fccc5a-0e0d-4682-805b-d5a6d47ac418  802-3-ethernet  eth1
```

I can issue `sudo nmcli connection modify eth0 connection.interface-name eth0` after logging in from the console as the vagrant user, but this works only sometimes; more often than not, the command has no effect. Only `sudo systemctl restart NetworkManager` seems to consistently fix the problem.

**Comment by Ranjandas** [comment]
Yes, this issue still exist. I have 2 versions of CentOS/7 vagrant image, and both has the same problem.

```
$ vagrant box list
centos/7                                        (virtualbox, 1509.01)
centos/7                                        (virtualbox, 1601.01)
```

I have tested this on following environments.

OS : OSX Yosemite, and Fedora 23
Vagrant Version : 1.8.1
VirtualBox Version : 5.0.14 r105127

The experience becomes worse when we are dealing with vagrant multi-host configurations.

**Comment by lpancescu** [comment]
@Ranjandas Are you also using VMs with more than one NICs? Vagrant will generate such a configuration, one network card via NAT, the other one host-only, if you set config.vm.network to "private_network".

@Ranjandas Did you also try with KVM instead of VirtualBox as a Vagrant provider? On Fedora, you can install it with "sudo dnf install vagrant-libvirt".

**Comment by Ranjandas** [comment]
@lpancescu Yes , I am using vm's with more than one NIC. One interface is NAT and the other is Host-Only Network.

I havent tried this with kvm.

**Comment by lpancescu** [comment]
@Ranjandas If I were you, I'd consider migrating to KVM on Linux (or VMWare Fusion on OS X, which is what the [official Vagrant documentation recommends](https://www.vagrantup.com/docs/providers/) over VirtualBox "for any real work"). Over 2-3 days of debugging and testing, we found a configuration issue with NetworkManager, but fixing it didn't improve the reliability when using VirtualBox as a provider. KVM was rock-solid in my tests, though. Please see my comment on PR #39.
